# .air_web.toml

root = "."
testdata_dir = "testdata"
tmp_dir = "tmp_web"

[build]
  cmd = "go build -o ./tmp_web/fbstocks ./cmd/fbstocks/main.go"
  bin = "./tmp_web/fbstocks"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp_web", "vendor", "testdata"]
  log = "build-errors.log"
  delay = 1000
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true

